### ISSUE TITLE
sync call

### ISSUE THREAD

**Issue by kildem** [e2ebridge/xslt4node#2]
is it possible to run xslt4node.transform(config) synchronously?

**Comment by p-muessig** [comment]
There are several node modules that may help you in doing what you want: http://stackoverflow.com/questions/16586640/node-js-async-to-sync

As there are synchronous versions of java module functions it would also be possible to implement a synchronous version directly.

**Comment by kildem** [comment]
Thanks for answer.
http://stackoverflow.com/questions/16586640/node-js-async-to-sync suggest deasync module, but it use uv.h library and it doesn't work with xslt4node. 

if I do:

     deasync(xslt4node.transform)(config)

I get this result:

     Assertion failed: (handle->type == UV_TCP || handle->type == UV_TTY || handle->type ==UV_NAMED_PIPE), function uv___stream_fd, file ../deps/uv/src/unix/stream.c, line 1510.
     Abort trap: 6


see: https://github.com/abbr/deasync/issues/7#event-239635348 
I think the best solution is your second suggestion to use synchronous versions of java module

**Comment by kildem** [comment]
it is a very good module it would be great if you will implement a sync version :)

**Comment by kildem** [comment]
it is a very good module it would be great if you will implement a sync version :)
As a quick fix (waiting a sync version) if I use node v0.12 child_process.execSync I can have a sync functionality.

**Comment by kildem** [comment]
In the documentation https://www.npmjs.com/package/xslt4node#transformsyncconfig-result
there's this function:


    transformSync(config) : result

but it is undefined!

**Comment by kildem** [comment]
Thank you very much! You have update the code ... it works!
