### ISSUE TITLE
xsl:include xslt bad path reference

### ISSUE THREAD

**Issue by rainabba** [e2ebridge/xslt4node#5]
First, thank you for this module. I very much need it to move from an IIS/ISAPI approach to node.js

In my current templates, I use the following successfully. With this transformer, I get an error that the included template can't be found and it's listed in the error as being relative to my node project folder (which is 2 folders higher than the original xslt and not referenced in this code anywhere).

```
<xsl:include href="RptHeader.xslt"/>
```
I've also tried:
```
<xsl:include href="./RptHeader.xslt"/>
```

The structure is:
```
/project
   /xml
      /xslt
          myTemplate.xslt (this includes "RptHeader.xslt")
          RptHeader.xslt
```

The error indicates that `/project/RptHeader.xslt` does not exist though. How do I fix this reference? My primary template shouldn't need a full path (and that would be a problem for our platform anyway as it's being migrated from another parser).

**Comment by p-muessig** [comment]
If your "config" looks like

    var config = {
        xsltPath: 'xml/xslt/myTemplate.xsl'
    };

try

    <xsl:include href="xml/xslt/RptHeader.xslt"/>

I hope that a relative path for the template is ok for you.

**Comment by p-muessig** [comment]
With version 0.2.1 relative URIs should work as expected (i.e. <xsl:include href="RptHeader.xslt"/> is ok).
