### ISSUE TITLE
Would it be possible to set JVM options like maximum heap size, etc.

### ISSUE THREAD

**Issue by jeltok** [e2ebridge/xslt4node#6]
Would it be possible to add a function set java options like maximum heap size for JVM, etc ?

It looks like our transformation process is running out of heap memory when dealing with huge files.

node-java allows to set JVM parameters using something like

`java.options.push('-Xmx1024m');`

It would be great to have an API method similar to one that adds a particular XSLT library to classpath?

**Comment by p-muessig** [comment]
Function 'addOptions(...options)' will be added in version 0.3.0.

**Comment by jeltok** [comment]
Thanks, the new function works perfectly!
