### ISSUE TITLE
async dependency - TypeError: null is not a function

### ISSUE THREAD

**Issue by git8808** [e2ebridge/xslt4node#8]
Hi, here is how dependencies looks like in package.json file after I install xslt4node using npm: 

` "dependencies": {
    "java": ">=0.3.1",
    "async": ">=0.4.0"
  }`

I am able to use transformSync() but having issues with transform(). On both Windows and Linux I'm getting **TypeError: null is not a function** message. Obviously there is  a problem with a version of async dependency. When I edit this dependency in node_modules/xslt4node/package.json file to `"async": "~=1.5.2"` everything works fine. 

I would be very grateful if you could fix this as I use this package a lot and it's bit frustrating to manually edit package.json each time I build an application.

Thank you!

**Comment by p-muessig** [comment]
Fixed with version 0.3.2.

**Comment by git8808** [comment]
Works as expected. Thanks!
